name: Build and deploy .NET Core application to Web App AspireDemoApi

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: AspireDemoApi20250212102651
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: Default-ActivityLogAlerts
  AZURE_APIM_SERVICENAME: AspireDemoApiapi
  AZURE_APIM_API_ID: AspireDemoApi
  AZURE_APIM_APPSERVICEURL: https://aspiredemoapi20250212102651.azurewebsites.net
  API_IMPORT_SPECIFICATION_PATH: ./publish/swagger.yaml
  API_IMPORT_DLL: ./publish/AspireDemoApi.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: AspireDemoApi.csproj
  DOTNET_ROOT: /usr/share/dotnet

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}

      - name: Build project
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Run tests
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build

      - name: Publish application
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Install Swashbuckle CLI .NET Global Tool
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 7.2.0

      - name: Ensure .NET Tools are in PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Verify Swashbuckle CLI Installation
        run: dotnet tool list --global

      - name: Generate Open API Specification Document
        run: |
          export PATH="$HOME/.dotnet/tools:$PATH"
          
          # Verify DLL Exists
          if [ ! -f "./publish/AspireDemoApi.dll" ]; then
            echo "❌ API DLL not found: ./publish/AspireDemoApi.dll"
            exit 1
          fi
          
          # Verify Swagger CLI Exists
          if ! command -v swagger &> /dev/null; then
            echo "❌ Swagger CLI tool not found! Installing..."
            dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 7.2.0
            export PATH="$HOME/.dotnet/tools:$PATH"
          fi
          
          # Confirm tool is installed
          dotnet tool list --global
          
          # Run Swagger Generation using explicit command
          swagger tofile --yaml --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" ${{ env.API_IMPORT_VERSION }} || (echo "❌ Swagger generation failed" && exit 1)

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Azure Login (Fixing JSON Issue)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Import API into Azure API Management
        run: |
          az apim api import \
            --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" \
            --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" \
            --service-name "${{ env.AZURE_APIM_SERVICENAME }}" \
            --api-id "${{ env.AZURE_APIM_API_ID }}" \
            --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" \
            --specification-path "${{ env.API_IMPORT_SPECIFICATION_PATH }}" \
            --specification-format OpenApi \
            --subscription-required false

      - name: Logout from Azure
        run: az logout
